config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :memberships
  resources :games, only: %i[index show] do
    resources :reviews
  end
  resources :borrowings, only: %i[new create index show]
  devise_for :users

  namespace :admin do
    resources :tags
    resources :borrowings
    resources :games do
      resources :reviews, except: %i[new create]
    end
    resources :users, except: %i[new create] do
      patch 'ban', on: :member
    end
  end

  # Error handling
  get 'public/403', to: 'errors#error403', as: 'error403'
  get 'public/404', to: 'errors#error404', as: 'error404'
  get 'public/422', to: 'errors#error422', as: 'error422'
  get 'public/500', to: 'errors#error500', as: 'error500'
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :user
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :set_membership, only: %i[show edit update destroy]

  def index
    @memberships = Membership.all
  end

  def show; end

  def new
    @membership = Membership.new
  end

  def edit; end

  def create
    @membership = Membership.new(membership_params)

    respond_to do |format|
      if @membership.save
        format.html { redirect_to membership_url(@membership), notice: 'Membership was successfully created.' }
        format.json { render :show, status: :created, location: @membership }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @membership.update(membership_params)
        format.html { redirect_to membership_url(@membership), notice: 'Membership was successfully updated.' }
        format.json { render :show, status: :ok, location: @membership }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @membership.destroy

    respond_to do |format|
      format.html { redirect_to memberships_url, notice: 'Membership was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_membership
    @membership = Membership.find(params[:id])
  end

  def membership_params
    params.require(:membership).permit(:active, :started_on, :expires_on, :user_id)
  end
end

app/views/memberships/_form.html.erb
<%= form_with(model: membership) do |form| %>
  <% if membership.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(membership.errors.count, "error") %> prohibited this membership from being saved:</h2>

      <ul>
        <% membership.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :active, style: "display: block" %>
    <%= form.check_box :active %>
  </div>

  <div>
    <%= form.label :started_on, style: "display: block" %>
    <%= form.date_field :started_on %>
  </div>

  <div>
    <%= form.label :expires_on, style: "display: block" %>
    <%= form.date_field :expires_on %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/memberships/_membership.html.erb
<div id="<%= dom_id membership %>">
  <p>
    <strong>Active:</strong>
    <%= membership.active %>
  </p>

  <p>
    <strong>Started on:</strong>
    <%= membership.started_on %>
  </p>

  <p>
    <strong>Expires on:</strong>
    <%= membership.expires_on %>
  </p>

  <p>
    <strong>User:</strong>
    <%= membership.user_id %>
  </p>

</div>

app/views/memberships/edit.html.erb
<h1>Editing membership</h1>

<%= render "form", membership: @membership %>

<br>

<div>
  <%= link_to "Show this membership", @membership %> |
  <%= link_to "Back to memberships", memberships_path %>
</div>

app/views/memberships/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Memberships</h1>

<div id="memberships">
  <% @memberships.each do |membership| %>
    <%= render membership %>
    <p>
      <%= link_to "Show this membership", membership %>
    </p>
  <% end %>
</div>

<%= link_to "New membership", new_membership_path %>

app/views/memberships/new.html.erb
<h1>New membership</h1>

<%= render "form", membership: @membership %>

<br>

<div>
  <%= link_to "Back to memberships", memberships_path %>
</div>

app/views/memberships/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @membership %>

<div>
  <%= link_to "Edit this membership", edit_membership_path(@membership) %> |
  <%= link_to "Back to memberships", memberships_path %>

  <%= button_to "Destroy this membership", @membership, method: :delete %>
</div>