config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :memberships
  resources :games, only: %i[index show] do
    resources :reviews
  end
  resources :borrowings, only: %i[new create index show]
  devise_for :users

  namespace :admin do
    resources :tags
    resources :borrowings
    resources :games do
      resources :reviews, except: %i[new create]
    end
    resources :users, except: %i[new create] do
      patch 'ban', on: :member
    end
  end

  # Error handling
  get 'public/403', to: 'errors#error403', as: 'error403'
  get 'public/404', to: 'errors#error404', as: 'error404'
  get 'public/422', to: 'errors#error422', as: 'error422'
  get 'public/500', to: 'errors#error500', as: 'error500'
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :borrowings
  has_many :users, through: :borrowings
  has_many :reviews
  has_and_belongs_to_many :tags
end

app/controllers/admin/games_controller.rb
module Admin
  class GamesController < ApplicationController
    before_action :authenticate_user!
    before_action :require_admin
    before_action :set_game, only: %i[show edit update destroy]

    def index
      @games = Game.all
    end

    def show; end

    def new
      @game = Game.new
    end

    def edit; end

    def create
      @game = Game.new(game_params)

      respond_to do |format|
        if @game.save
          format.html { redirect_to admin_game_url(@game), notice: 'Game was successfully created.' }
          format.json { render :show, status: :created, location: @game }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @game.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      respond_to do |format|
        if @game.update(game_params)
          format.html { redirect_to admin_game_url(@game), notice: 'Game was successfully updated.' }
          format.json { render :show, status: :ok, location: @game }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @game.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @game.destroy

      respond_to do |format|
        format.html { redirect_to admin_games_url, notice: 'Game was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private

    def set_game
      @game = Game.find(params[:id])
    end

    def game_params
      params.require(:game).permit(:name, :description, :min_players,
                                   :max_players, :language, :min_age, :brand, :stock, tag_ids: [])
    end

    def require_admin
      unless current_user.admin?
        flash[:alert] = 'Forbidden'
        redirect_to root_path # halts request cycle
      end
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: %i[show]

  def index
    @games = Game.all
  end

  def show; end

  private

  def set_game
    @game = Game.find(params[:id])
  end
end

app/views/admin/games/_form.html.erb
<%= form_with(model: [:admin, game]) do |form| %>
  <% if game.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% game.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :min_players, style: "display: block" %>
    <%= form.number_field :min_players %>
  </div>
  
  <div>
    <%= form.label :max_players, style: "display: block" %>
    <%= form.number_field :max_players %>
  </div>

  <div>
    <%= form.label :language, style: "display: block" %>
    <%= form.number_field :language %>
  </div>

  <div>
    <%= form.label :min_age, style: "display: block" %>
    <%= form.number_field :min_age %>
  </div>

  <div>
    <%= form.label :brand, style: "display: block" %>
    <%= form.text_field :brand %>
  </div>

  <div>
    <%= form.label :stock, style: "display: block" %>
    <%= form.number_field :stock %>
  </div>

  <div>
    <%= form.label :tags, style: "display: block" %>
    <%= form.collection_check_boxes :tag_ids, Tag.order(:name), :id, :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/games/_game.html.erb
<div id="<%= dom_id game %>">
  <p>
    <strong>Name:</strong>
    <%= game.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= game.description %>
  </p>

  <p>
    <strong>Min number of players:</strong>
    <%= game.min_players %>
  </p>
  
  <p>
    <strong>Max number of players:</strong>
    <%= game.max_players %>
  </p>
  
  <p>
    <strong>Language:</strong>
    <%= game.language %>
  </p>

  <p>
    <strong>Min age:</strong>
    <%= game.min_age %>
  </p>

  <p>
    <strong>Brand:</strong>
    <%= game.brand %>
  </p>

  <p>
    <strong>Stock:</strong>
    <%= game.stock %>
  </p>

  <strong>Tags:</strong>
    <ul>
      <% game.tags.each do |tag|%>
        <li>
          <%= tag.name %>
        </li>
      <% end %>
    </ul>
</div>

app/views/admin/games/edit.html.erb
<h1>Editing game</h1>

<%= render "form", game: @game %>

<br>

<div>
  <%= link_to "Show this game", admin_game_url(@game) %> |
  <%= link_to "Back to games", admin_games_path %>
</div>

app/views/admin/games/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Games</h1>


<div id="games">
  <% @games.each do |game| %>
    <p>
      <%= link_to game.name, admin_game_url(game) %>
    </p>
  <% end %>
</div>

<%= link_to "New game", new_admin_game_path %>

app/views/admin/games/new.html.erb
<h1>New game</h1>

<%= render "form", game: @game %>

<br>

<div>
  <%= link_to "Back to games", admin_games_path %>
</div>

app/views/admin/games/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @game %>

<div>
  <%= link_to "Edit this game", edit_admin_game_path(@game) %> |
  <%= link_to "Back to games", admin_games_path %>

  <%= button_to "Destroy this game", @admin_game, method: :delete %>
</div>