config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :memberships
  resources :games, only: %i[index show] do
    resources :reviews
  end
  resources :borrowings, only: %i[new create index show]
  devise_for :users

  namespace :admin do
    resources :tags
    resources :borrowings
    resources :games do
      resources :reviews, except: %i[new create]
    end
    resources :users, except: %i[new create] do
      patch 'ban', on: :member
    end
  end

  # Error handling
  get 'public/403', to: 'errors#error403', as: 'error403'
  get 'public/404', to: 'errors#error404', as: 'error404'
  get 'public/422', to: 'errors#error422', as: 'error422'
  get 'public/500', to: 'errors#error500', as: 'error500'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum role: { admin: 0, non_enrolled: 1, council: 2, member: 3, banned: 5 }, _default: :non_enrolled

  has_many :borrowings
  has_many :reviews
  has_many :games, through: :borrowings
  has_one :membership, dependent: :destroy

  validates :email,
            presence: true,
            uniqueness: { case_sensitive: false,
                          message: 'There is already an account with this email' },
            length: { minimum: 3, maximum: 254 },
            format: { with: URI::MailTo::EMAIL_REGEXP,
                      message: 'The email does not have a valid format' }
  validates :phone,
            format: { with: /\A\d{9}\z/,
                      message: 'The phone number does not have a valid format' },
            allow_nil: true,
            allow_blank: true

  LEGAL_AGE = 18
  def fullname
    "#{name} #{surname}".strip
  end

  def underage?
    age < LEGAL_AGE
  end

  def ban!
    banned!
  end

  def active_for_authentication?
    super && active?
  end

  def inactive_message
    active? ? super : :locked
  end

  def ever_borrowed?(game)
    borrowings.where(game:).any?
  end

  def ever_reviewed?(game)
    reviews.where(game:).any?
  end

  private

  def active?
    !banned?
  end

  def age
    today = Date.today

    today.year - birthdate.year - (if (today.month > birthdate.month) ||
    today.month == birthdate.month && today.day >= birthdate.day
                                     0
                                   else
                                     1
                                   end)
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < ApplicationController
    before_action :authenticate_user!
    before_action :require_admin
    before_action :set_user, only: %i[show edit update destroy ban]
    # GET /users or /users.json
    def index
      @users = User.all
    end

    # GET /users/1 or /users/1.json
    def show; end

    # GET /users/1/edit
    def edit; end

    # PATCH/PUT /users/1 or /users/1.json
    def update
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to admin_user_url(@user), notice: 'User was successfully updated.' }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /users/1 or /users/1.json
    def destroy
      @user.destroy

      respond_to do |format|
        format.html { redirect_to admin_users_url, notice: 'User was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    # PATCH /users/1/ban
    def ban
      @user.ban!

      respond_to do |format|
        format.html { redirect_to admin_users_url, notice: 'User was successfully banned.' }
        format.json { head :no_content }
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      # TO-DO I should change this to only the parameters that the admin is able to modify
      params.require(:user).permit(:name, :password, :surname, :email, :phone, :address, :birthdate, :nickname, :role)
    end

    def require_admin
      unless current_user.admin?
        flash[:alert] = 'Forbidden'
        redirect_to root_path # halts request cycle
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users/1 or /users/1.json
  def show; end

  # GET /users/1/edit
  def edit; end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    # TO-DO I should change this to only the parameters that an user is able to modify
    params.require(:user).permit(:name, :password, :surname, :email, :phone, :address, :birthdate)
  end
end

app/views/admin/users/_form.html.erb
<%= form_with(model: [:admin, user]) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :surname, style: "display: block" %>
    <%= form.text_field :surname %>
  </div>

  <div>
    <%= form.label :nickname, style: "display: block" %>
    <%= form.text_field :nickname %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.email_field :email %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :birthdate, style: "display: block" %>
    <%= form.date_field :birthdate %>
  </div>

  <div>
    <%= form.label :role, style: "display: block" %>
    <%= form.select :role, ["admin","non_enrolled","council", "member","banned"] %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Surname:</strong>
    <%= user.surname %>
  </p>

  <p>
    <strong>Nickname:</strong>
    <%= user.nickname %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= user.phone %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= user.address %>
  </p>

  <p>
    <strong>Birthdate:</strong>
    <%= user.birthdate %>
  </p>

  <p>
    <strong>Role:</strong>
    <%= user.role %>
  </p>

</div>

app/views/admin/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", admin_user_url(@user) %> |
  <%= link_to "Back to users", admin_users_path %>
</div>

app/views/admin/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>|
      <%= link_to "Ban this user", ban_admin_user_path(user), data: {
        turbo_method: :patch,
        turbo_confirm: "Are you sure you want to ban this user?"
        } %> |
      <%= link_to "Show this user", admin_user_url(user) %> |
    </p>
  <% end %>
</div>

app/views/admin/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  | <%= link_to "Edit this user", edit_admin_user_path(@user) %> |
  <%= link_to "Ban this user", ban_admin_user_path, data: {
    turbo_method: :patch,
    turbo_confirm: "Are you sure you want to ban this user?"
    } %> |
  <%= link_to "Destroy this user", @admin_user, data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure you want to delete this user?"
    } %> |
    <br>
  <%= link_to "Back to users", admin_users_path %>
</div>